### ISSUE TITLE
关于在ios上裁剪，最后上传的像素固定在了320*160

### ISSUE THREAD

**Issue by a1029563229** [apicloudcom/FNImageClip-Example#1]
就是同一张图，安卓手机裁剪后提交到后台是880*440  或者更高的分辨率（跟图片本身的分辨率有关），，但是ios上。不管裁剪多大分辨率的图片。都会变成320*160上传。
希望能够得到回复，万分感谢

**Comment by a1029563229** [comment]
@IT-SDJ

**Comment by IT-SDJ** [comment]
在[FNImageClip](http://docs.apicloud.com/Client-API/Func-Ext/FNImageClip#a1)模块的open方法中，有一个参数highDefinition参数(截图时是否截取与原图分辨率一致的图)，该参数的默认值为false，根据你的问题需求，只要将该参数定义为**true**就可以了

**Comment by a1029563229** [comment]
@IT-SDJ 我打包过后发现还是不行，我仔细看了文档好几遍，都不行，能不能测试一下，我这边确实不行，这个问题严重影响到项目，真的非常急，求解决 万分感谢

**Comment by a1029563229** [comment]
@IT-SDJ 晚点我把截图给你看看，确实是按照文档配置的

**Comment by IT-SDJ** [comment]
我刚刚又实测一次，没有发现你描述的问题，我使用iphone6s手机，在save方法中，设置copyToAlbum: true将裁剪后的图片同步保存到系统相册，我通过iphone分享将图片传到mac电脑查看这个图片的信息，是按照我设定的截图尺寸截图的，并没有出现你描述的都会变成320x160，你可以按我描述的方法验证一下。

**Comment by a1029563229** [comment]
@IT-SDJ 你好 我们都是按你的参数设置的 但是不行 能不能加个QQ或者微信 
我们想有偿请你帮我们看看这个问题 把文件打包给我们 然后我们测试通过了就行了 就这个问题
我们急着上线 所以没有太多时间了 可以吗

**Comment by IT-SDJ** [comment]
3349064464@qq.com，加入申请时加入“github问题咨询“
